[project]
name = "ts-ssl-label-noise"
version = "0.1.0"
description = "Self-Supervised Learning for Label Noise Correction in Time Series Classification"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
